// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"context"
	"database/sql"
	"time"
)

type Querier interface {
	CreateOrUpdateUserStats(ctx context.Context, arg CreateOrUpdateUserStatsParams) (UserStat, error)
	CreateStudySession(ctx context.Context, arg CreateStudySessionParams) (StudySession, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// For top 10 users
	DeleteOldStudySessions(ctx context.Context, startTime time.Time) error
	EndStudySession(ctx context.Context, arg EndStudySessionParams) (StudySession, error)
	GetActiveStudySession(ctx context.Context, userID sql.NullString) (StudySession, error)
	GetLeaderboard(ctx context.Context) ([]GetLeaderboardRow, error)
	GetUser(ctx context.Context, userID string) (User, error)
	GetUserStats(ctx context.Context, userID string) (UserStat, error)
	// $1 will be the cutoff timestamp (e.g., 6 months ago)
	// Calendar Day-Based User Streaks Queries
	GetUserStreak(ctx context.Context, arg GetUserStreakParams) (GetUserStreakRow, error)
	GetUsersForDailyEvaluation(ctx context.Context, streakEvaluatedDate sql.NullTime) ([]GetUsersForDailyEvaluationRow, error)
	GetUsersForStreakReset(ctx context.Context, lastActivityDate sql.NullTime) ([]GetUsersForStreakResetRow, error)
	GetUsersNeedingWarnings(ctx context.Context, lastActivityDate sql.NullTime) ([]GetUsersNeedingWarningsRow, error)
	HasActivityForDate(ctx context.Context, arg HasActivityForDateParams) (bool, error)
	ResetAllStreakDailyFlags(ctx context.Context) error
	ResetDailyStudyTime(ctx context.Context) error
	ResetMonthlyStudyTime(ctx context.Context) error
	// Haven't been active today
	ResetUserStreakCount(ctx context.Context, arg ResetUserStreakCountParams) error
	ResetWeeklyStudyTime(ctx context.Context) error
	StartDailyActivity(ctx context.Context, arg StartDailyActivityParams) (StartDailyActivityRow, error)
	UpdateDailyActivityMinutes(ctx context.Context, arg UpdateDailyActivityMinutesParams) error
	UpdateStreakImmediately(ctx context.Context, arg UpdateStreakImmediatelyParams) error
	// $1 is today's date in Manila timezone
	UpdateUserStreakAfterEvaluation(ctx context.Context, arg UpdateUserStreakAfterEvaluationParams) (UpdateUserStreakAfterEvaluationRow, error)
	// Haven't been warned today
	UpdateWarningNotifiedAt(ctx context.Context, arg UpdateWarningNotifiedAtParams) error
}

var _ Querier = (*Queries)(nil)
